# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a6d1208423cac9e72b0478bbd9cd087d561656d0ee8816b4a2efce157c65275cbf0e6267b6dc91ae489db9f7f1d2fb0031cff897431eff6fd6424fdf17bf49

test:
  secret_key_base: c2f95637f87b9666029ca8ffe08e3cf882dccdb7a799183bc139e447190db797daa74fe85db0d7a62e12939794e682fee3e498b36f31b0bf5d818389c4cb8f53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
